config/routes.rb
MapTrack::Application.routes.draw do

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }, :controllers => { :sessions => 'sessions', :registrations => 'registrations' }

  root :to => "tracks#index"

  resources :tracks do
    put 'close' => 'tracks#close'
    get 'coordinates/last' => 'coordinates#show_last'
    resources :coordinates do
      get 'place' => 'coordinates#place'
    end
    resources :places
    resources :comments
  end

  get 'tracks/public/:share_token' => 'tracks#show'
  get 'tracks/public/:share_token/places' => 'places#index'
  get 'tracking/:token/track' => 'tracking#track'

  get 'user' => 'users#index'
  get 'user/search' => 'users#search'
  get 'user/_/edit' => 'users#edit', :as => 'edit_user'
  put 'user' => 'users#update'
  patch 'user' => 'users#update'
  match 'user/:name.:format' => 'users#show', :via => [:get], :constraints => {:name => /.*/}, :format => false

  post 'friendship' => 'friendships#request_friendship'
  put 'friendship/:id/confirm' => 'friendships#confirm_friendship'
  patch 'friendship/:id/confirm' => 'friendships#confirm_friendship'
  delete 'friendship/:id' => 'friendships#destroy_friendship'

  get 'stories' => 'stories#index'
  get 'stories/unseen/count' => 'stories#unseen_count'
  put 'stories/seen' => 'stories#seen_all'
  get 'stories/:id' => 'stories#show'
  put 'stories/:id/seen' => 'stories#seen'
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :name, :public, :share_token

  belongs_to :user
  has_many :coordinates, :order => "time"

  has_one_document :summary
  has_many_documents :comments

  scope :for_user, lambda {|user| where("user_id = ?", user.id)}
  scope :visible_for_user, lambda {|user|
    where("user_id = ? or (user_id in (?) and public=?)", user.id, user.friends, true)
  }

  validates :name, :presence => true
  validates :summary, :presence => true
  validates :share_token, :uniqueness => true

  before_save do
    self.public = false if self.public.nil?
    self.share_token = Devise.friendly_token if self.share_token.nil?
  end

  after_create do
    Story.new(track: self, user: self.user, action: "started a new track").save
  end

  def to_json(options={})
    super(:include => [:coordinates, :summary])
  end

  def old?
    return false if coordinates.empty?
    coordinates.last.is_a_long_time_after? Time.now
  end

  def close!
    destination = coordinates.last
    destination.user_id = user_id
    destination.delay.set_place!
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  include TracksHelper

  before_filter do
    find_shared_track or authenticate_user!
  end

  # GET /tracks
  # GET /tracks.json
  def index
    @my_tracks = tracks_for_current_user
    @friends_tracks = tracks_for_friends_of_current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @my_tracks + @friends_tracks, :include => :summary }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    unless @track
      @track = track_accessible_for_current_user params[:id]
      @track.summary.set_format MetricSystem.new
    end
    readonly = (@track.user != current_user)

    respond_to do |format|
      format.html { render :partial => 'tracks/show', :locals => { :track => @track, :readonly => readonly } }
      format.json { render json: @track }
      format.xml
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.json { render json: @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = track_owned_by_current_user params[:id]

    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])
    @track.user = current_user

    respond_to do |format|
      if @track.save
        format.html { redirect_to tracks_path, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = track_owned_by_current_user params[:id]

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = track_owned_by_current_user params[:id]
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end

  # PUT /tracks/1/close
  def close
    track = track_owned_by_current_user params[:id]
    track.close!

    respond_to do |format|
      format.html { redirect_to @track, notice: 'Track was successfully closed.' }
      format.json { head :no_content }
    end
  end

  private

  def tracks_for_current_user
    Track.for_user current_user
  end

  def tracks_for_friends_of_current_user
    Track.find_all_by_user_id_and_public(current_user.friends.select{|u| u.id}, true)
  end

  # Returns the track with given id if it is owned by current_user
  def track_owned_by_current_user(id)
    tracks_for_current_user.find id
  end

  # Returns the track with given id if it is accessible for current_user
  def track_accessible_for_current_user(id)
    Track.find_by_id_and_user_id(id, current_user.friends.select{|u| u.id} + [current_user.id])
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def find_shared_track
    @track = Track.find_by_public_and_share_token(true, params[:share_token]) if params[:share_token]
  end
end

app/views/tracks/_form.html.erb
<div class="body">
  <div class="cell">
    <%= form_for(@track, :remote => true) do |f| %>
      <%= f.text_field :name %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/tracks/_info.html.erb
<% info = track.summary %>
<% if info %>
<div class="col size1of3">
  <span class="icon icon-time"></span>&nbsp;<%= info.duration %>
</div>
<div class="col size1of3">
  <span class="icon icon-road"></span>&nbsp;<%= info.distance %>&nbsp;km<br />
  <span class="icon icon-circle-arrow-up"></span>&nbsp;&nbsp;<%= info.rise %><br />
  <span class="icon icon-circle-arrow-down"></span>&nbsp;&nbsp;<%= info.fall %>
</div>
<div class="col size1of3">
  <span class="icon icon-dashboard"></span>&nbsp;<%= info.average_speed %>
</div>
<% end %>

app/views/tracks/_list.html.erb
<% unless tracks.empty? %>
  <div class="col size1of2">
    <div class="cell">
      <div class="fatty">
        <%= title %>
      </div>
      <% tracks.each do |track| %>
        <%= render :partial => 'tracks/show', :locals => { :track => track, :readonly => readonly } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tracks/_place.html.erb
<ul>
  <%
  start = true
  last = track.coordinates.last

  track.coordinates.each do |coord|
    unless coord.place.data.nil?
      name = coord.place.data["display_name"]
      shortname = name.split(", ", 3)[0..1].join ", " unless name.nil?
    else
      shortname = nil
    end

    if start
      start = false
      text = "from"
    elsif coord == track.coordinates.last
      text = "to"
    else
      next if shortname.nil?
      text = "via"
    end %>

    <div class="col size1of6"><%= text %></div>
    <div class="col sizefill">
      <% if shortname %>
        <a title="<%= name %>"><%= shortname %></a>
      <% else %>
        ?
      <% end %>
    </div>
<% end %>
</ul>

app/views/tracks/_show.html.erb
<div class="cell panel" id="track<%= track.id %>">
  <div class="gradient header">
    <%= track.name %>
  </div>
  <div class="body">
    <div class="cell">
      <div class="col size6of8">
        <% if readonly %>
          <div class="cell">
            <%= render :partial => 'users/userlink', :locals => { :user => track.user } %>
          </div>
        <% end %>
        <%= render :partial => 'tracks/place', :locals => { :track => track } %>
        <div class="cell">
          <%= render :partial => 'tracks/info', :locals => { :track => track } %>
        </div>
      </div>
      <div class="col sizefill" style="text-align:right">
        <a href="#" onclick='mapView.addTrack("/tracks/<%= track.id %>.xml", "<%= track.name %>")' class="icon icon-eye-open"> show</a>
        <br />
        <% unless readonly %>
          <%= link_to ' edit', edit_track_path(track), :class => 'icon icon-edit', :remote => true, :'data-target' => '#track'+track.id.to_s %><br />
          <%= link_to ' destroy', track, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'icon icon-remove' %>
        <% end %>
      </div>
    </div>
    <div class="cell">
      <!-- TODO fill in some information about the track -->
    </div>
  </div>
</div>

app/views/tracks/index.html.erb
<%= render :partial => 'layouts/header', :locals => {:title => "Tracks"} %>

<%= render :partial => 'list', :locals => {:tracks => @my_tracks, :title => "My tracks", :readonly => false} %>
<%= render :partial => 'list', :locals => {:tracks => @friends_tracks, :title => "My friends' tracks", :readonly => true} %>

app/views/tracks/show.xml.erb
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx version="1.1" creator="MapTrack">
  <metadata>
    <name><%= @track.name %></name>
  </metadata>
  <trk>
    <trkseg>
    <% @track.coordinates.each { |c| %>
      <trkpt lat="<%= c.latitude %>" lon="<%= c.longitude %>">
      <% unless c.elevation==nil %>
        <ele><%= c.elevation %></ele>
      <% end %>
      <% unless c.time==nil %>
        <time><%= c.time.iso8601 %></time>
      <% end %>
      <% unless c.place.data==nil %>
        <name><%= c.place.data["display_name"] %></name>
      <% end %>
      </trkpt>
    <% } %>
    </trkseg>
  </trk>
</gpx>