config/routes.rb
MapTrack::Application.routes.draw do

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }, :controllers => { :sessions => 'sessions', :registrations => 'registrations' }

  root :to => "tracks#index"

  resources :tracks do
    put 'close' => 'tracks#close'
    get 'coordinates/last' => 'coordinates#show_last'
    resources :coordinates do
      get 'place' => 'coordinates#place'
    end
    resources :places
    resources :comments
  end

  get 'tracks/public/:share_token' => 'tracks#show'
  get 'tracks/public/:share_token/places' => 'places#index'
  get 'tracking/:token/track' => 'tracking#track'

  get 'user' => 'users#index'
  get 'user/search' => 'users#search'
  get 'user/_/edit' => 'users#edit', :as => 'edit_user'
  put 'user' => 'users#update'
  patch 'user' => 'users#update'
  match 'user/:name.:format' => 'users#show', :via => [:get], :constraints => {:name => /.*/}, :format => false

  post 'friendship' => 'friendships#request_friendship'
  put 'friendship/:id/confirm' => 'friendships#confirm_friendship'
  patch 'friendship/:id/confirm' => 'friendships#confirm_friendship'
  delete 'friendship/:id' => 'friendships#destroy_friendship'

  get 'stories' => 'stories#index'
  get 'stories/unseen/count' => 'stories#unseen_count'
  put 'stories/seen' => 'stories#seen_all'
  get 'stories/:id' => 'stories#show'
  put 'stories/:id/seen' => 'stories#seen'
end

app/models/coordinate.rb
class Coordinate < ActiveRecord::Base
  attr_accessor :user_id
  attr_accessible :track_id, :latitude, :longitude, :time, :elevation

  belongs_to :track

  has_one_document :place

  after_save do
    track.summary.update!
    self.delay.set_place
  end

  scope :for_user, lambda {|user| where("user_id = ?", user.id).joins(:track).readonly(false)}

  validate :user_may_access_track
  validates :latitude, :numericality => true
  validates :longitude, :numericality => true
  validates :elevation, :numericality => true, :allow_nil => true

  def set_place
    may_set_place false
  end

  def set_place!
    may_set_place true
  end

  def is_a_long_time_after? t
    return false if track.summary.average_interval == 0.0
    (time.to_i - t.to_i).abs > (10 * track.summary.average_interval)
  end

  def distance_to coord
    # http://stackoverflow.com/questions/365826/calculate-distance-between-2-gps-coordinates
    dlat = (coord.latitude - latitude) * Math::PI / 180
    dlon = (coord.longitude - longitude) * Math::PI / 180
    lat1 = latitude * Math::PI / 180
    lat2 = coord.latitude * Math::PI / 180

    a = Math.sin(dlat/2) * Math.sin(dlat/2) +
            Math.sin(dlon/2) * Math.sin(dlon/2) * Math.cos(lat1) * Math.cos(lat2)
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
    6371000 * c
  end

  def to_json(options={})
    super(:include => :place)
  end

  private

  def user_may_access_track
    if track_id == nil or user_id != track.user_id
      errors.add(:track, "is not yours")
    end
  end

  def query_place
    query = Nominatim::Reverse.new
    query.lat latitude
    query.lon longitude
    query.fetch
  end

  def may_set_place(forced)
    return if self.place.data

    coords = track.coordinates
    if self.persisted? and coords.first != self
      prev = coords.where("id < ?", id).order("id").last
    else
      prev = coords.last
    end

    if forced or coords.first == self or prev.nil? or is_a_long_time_after? prev.time
      place = self.place
      place.data = query_place.instance_variable_get(:@attrs) unless self.place.data
      place.save
      return true
    end
  end
end

app/controllers/coordinates_controller.rb
class CoordinatesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_track

  # GET /coordinates
  # GET /coordinates.json
  def index
    @coordinates = @track.coordinates.for_user current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coordinates }
    end
  end

  # GET /coordinates/1
  # GET /coordinates/1.json
  def show
    @coordinate = coordinate_for_current_user params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coordinate }
    end
  end

  def show_last
    params[:id] = @track.coordinates.last.id
    show
  end

  # GET /coordinates/1/place(.:format)
  def place
    @coordinate = coordinate_for_current_user params[:coordinate_id]
    place = @coordinate.place
    if place.nil? or place.data.nil?
      head :not_found
      return
    end
    respond_to do |format|
      format.json { render json: place }
    end
  end

  # GET /coordinates/new
  # GET /coordinates/new.json
  def new
    @coordinate = Coordinate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coordinate }
    end
  end

  # GET /coordinates/1/edit
  def edit
    @coordinate = coordinate_for_current_user params[:id]
  end

  # POST /coordinates
  # POST /coordinates.json
  def create
    @coordinate = @track.coordinates.build(params[:coordinate])
    @coordinate.user_id = current_user.id

    respond_to do |format|
      if @coordinate.save
        format.html { redirect_to [@track, @coordinate], notice: 'Coordinate was successfully created.' }
        format.json { render json: @coordinate, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @coordinate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /coordinates/1
  # PUT /coordinates/1.json
  def update
    @coordinate = coordinate_for_current_user params[:id]
    @coordinate.user_id = current_user.id

    respond_to do |format|
      if @coordinate.update_attributes(params[:coordinate])
        format.html { redirect_to [@track, @coordinate], notice: 'Coordinate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coordinate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinates/1
  # DELETE /coordinates/1.json
  def destroy
    @coordinate = coordinate_for_current_user params[:id]
    @coordinate.destroy

    respond_to do |format|
      format.html { redirect_to track_coordinates_url }
      format.json { head :no_content }
    end
  end

  private

  def coordinate_for_current_user id
    @track.coordinates.for_user(current_user).find id
  end

  def find_track
    @track = Track.find params[:track_id]
  end
end

app/helpers/coordinates_helper.rb
module CoordinatesHelper

end

app/views/coordinates/_form.html.erb
<%= form_for([@track, @coordinate]) do |f| %>
  <% if @coordinate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coordinate.errors.count, "error") %> prohibited this coordinate from being saved:</h2>

      <ul>
      <% @coordinate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.number_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %>
    <%= f.number_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :elevation %>
    <%= f.number_field :elevation %>
  </div>
    <div class="field">
    <%= f.label :time %>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coordinates/edit.html.erb
<h1>Editing coordinate</h1>

<%= render 'form' %>

<%= link_to 'Show', [@track, @coordinate] %> |
<%= link_to 'Back', track_coordinates_path %>

app/views/coordinates/index.html.erb
<h1>Listing coordinates</h1>

<table>
  <tr>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Elevation</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coordinates.each do |coordinate| %>
  <tr>
    <td><%= coordinate.latitude %></td>
    <td><%= coordinate.longitude %></td>
    <td><%= coordinate.elevation %></td>
    <td><%= coordinate.time %></td>
    <td><%= link_to 'Show', [@track, coordinate] %></td>
    <td><%= link_to 'Edit', edit_track_coordinate_path(@track, coordinate) %></td>
    <td><%= link_to 'Destroy', [@track, coordinate], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Coordinate', new_track_coordinate_path %>

app/views/coordinates/new.html.erb
<h1>New coordinate</h1>

<%= render 'form' %>

<%= link_to 'Back', track_coordinates_path %>

app/views/coordinates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @coordinate.latitude %>
</p>
<p>
  <b>Longitude:</b>
  <%= @coordinate.longitude %>
</p>
<p>
  <b>Elevation:</b>
  <%= @coordinate.elevation %>
</p>
<p>
  <b>Time:</b>
  <%= @coordinate.time %>
</p>

<%= link_to 'Edit', edit_track_coordinate_path(@track, @coordinate) %> |
<%= link_to 'Back', track_coordinates_path %>